#!/usr/bin/env pwsh
# cleanup.ps1 — Remove all Azure resources and local configuration
# Safe to run multiple times. If resources don't exist, steps are skipped.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "=== Data Crunch Agent — Cleanup ===" -ForegroundColor Cyan
Write-Host ""

$cleanedUp = @()

# --- Delete Azure resources ---
if (Test-Path ".azure") {
    Write-Host "⏳ Deleting Azure resources with 'azd down --purge --force'..." -ForegroundColor Yellow
    try {
        azd down --purge --force
        if ($LASTEXITCODE -eq 0) {
            $cleanedUp += "✅ Azure resources deleted"
            Write-Host "Azure resources deleted." -ForegroundColor Green
        } else {
            Write-Host "⚠️  'azd down' returned a non-zero exit code. Some resources may remain." -ForegroundColor Yellow
            $cleanedUp += "⚠️  Azure resources may not be fully deleted"
        }
    } catch {
        Write-Host "⚠️  Could not run 'azd down'. You may need to delete resources manually in the Azure portal." -ForegroundColor Yellow
        $cleanedUp += "⚠️  Azure resource deletion skipped (azd not available)"
    }
} else {
    Write-Host "ℹ️  No .azure/ folder found — skipping Azure resource deletion." -ForegroundColor DarkGray
    $cleanedUp += "ℹ️  No Azure resources to delete (.azure/ not found)"
}

# --- Delete local .azure folder ---
if (Test-Path ".azure") {
    Write-Host "🗑️  Removing .azure/ folder..." -ForegroundColor Yellow
    Remove-Item -Path ".azure" -Recurse -Force
    $cleanedUp += "✅ .azure/ folder removed"
    Write-Host ".azure/ folder removed." -ForegroundColor Green
}

# --- Delete azure.yaml (generated by azd init) ---
if (Test-Path "azure.yaml") {
    Write-Host "🗑️  Removing azure.yaml (generated by azd init)..." -ForegroundColor Yellow
    Remove-Item -Path "azure.yaml" -Force
    $cleanedUp += "✅ azure.yaml removed"
    Write-Host "azure.yaml removed." -ForegroundColor Green
}

# --- Delete .env file if present ---
if (Test-Path ".env") {
    Write-Host "🗑️  Removing .env file..." -ForegroundColor Yellow
    Remove-Item -Path ".env" -Force
    $cleanedUp += "✅ .env file removed"
    Write-Host ".env file removed." -ForegroundColor Green
}

# --- Restore agent.yaml to repo version (azd ai agent init modifies it) ---
$agentYaml = "$PSScriptRoot/src/DataCrunchAgent/agent.yaml"
if (Test-Path $agentYaml) {
    Write-Host "🔄 Restoring agent.yaml to repo version..." -ForegroundColor Yellow
    git checkout -- $agentYaml 2>$null
    if ($LASTEXITCODE -eq 0) {
        $cleanedUp += "✅ agent.yaml restored to repo version"
        Write-Host "agent.yaml restored." -ForegroundColor Green
    } else {
        Write-Host "⚠️  Could not restore agent.yaml via git — it may already be clean." -ForegroundColor DarkGray
    }
}

# --- Clear .NET User Secrets ---
$csprojPath = "$PSScriptRoot/src/DataCrunchAgent/DataCrunchAgent.csproj"
if (Test-Path $csprojPath) {
    Write-Host "🗑️  Clearing .NET User Secrets..." -ForegroundColor Yellow
    dotnet user-secrets clear --project $csprojPath > $null 2>&1
    $cleanedUp += "✅ .NET User Secrets cleared"
    Write-Host "User Secrets cleared." -ForegroundColor Green
} else {
    Write-Host "ℹ️  Project file not found — skipping User Secrets cleanup." -ForegroundColor DarkGray
}

# --- Print cleanup summary ---
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Cleanup Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
foreach ($item in $cleanedUp) {
    Write-Host "  $item"
}
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Cleanup complete! Run setup.ps1 to start fresh." -ForegroundColor Green
Write-Host ""
